config/routes.rb
Rails.application.routes.draw do

  devise_for :customers
  root 'welcome#index'

  resources :orders, :customers

  get '/orders/:id/shipping_info' => 'orders#shipping_info', as: :order_shipping_info



end

app/models/concerns/order_count_observer.rb
module OrderCountObserver
  extend ActiveSupport::Concern

  included do
    after_save :increse_count,:increse_total_sold_unit
    after_save :order_feeds, if: :customer
  end

  def increse_count
    Pusher['broadcast'].trigger!('total_order_shipped', value: Order.shipped.count)
  end

  def increse_total_sold_unit
    Pusher['broadcast'].trigger!('total_units_sold', value: Order.units_sold)
  end

  def order_feeds
   Pusher['broadcast'].trigger!('order_feeds', {value: "#{order.customer.first_name} just purchased from #{order.customer.city}, #{order.customer.country}",id: order.id})
  end
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## validations
  validates :first_name, :last_name, :country, :postal_code, :city, presence: true
  ## association
  has_many :orders, dependent: :destroy

end

app/models/order.rb
class Order < ActiveRecord::Base
  include OrderCountObserver
  ## associations
  belongs_to :customer
  has_and_belongs_to_many :products
  # #scopes
  scope :shipped, -> { where(shipped: true) }
  scope :completed, -> { where(complete: true) }
  scope :lastest_order, -> { order("id desc").limit(5)}

  def add_product(product_name, qty)
    product = Product.where(name: product_name).first
    # set the product qty
    product.qty = qty.to_i
    product.order_id = id
    products << product
    products.last.save!
    update_total_cost(product.cost, qty)
  end

  def update_total_cost(product_cost, qty)
    product_cost *= qty.to_i
    self.total_cost += product_cost
  end

  def confirm
    self.shipped = true
    self.complete = true
    self.save!
  end

  def self.units_sold
    total_units = 0
    orders = Order.shipped.includes(:products)
    orders.each do |order|
      order.products.each do |product|
        if product.name == 'Six Pack'
          total_units += 12 * product.qty.to_i
        elsif product.name == 'Bomber'
          total_units += product.qty.to_i
        end
      end
    end
    total_units
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_and_belongs_to_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # if customer is logged in, return current_customer, else return guest_customer
  def current_or_guest_customer
    if current_customer
      if session[:guest_user_id] && session[:guest_user_id] != current_customer.id
        logging_in
        guest_customer(with_retry = false).try(:destroy)
        session[:guest_user_id] = nil
      end
      current_customer
    else
      guest_customer
    end
  end

  # find guest_customer object associated with the current session,
  # creating one as needed
  def guest_customer(with_retry = true)
    # Cache the value the first time it's gotten.
    @cached_guest_user ||= Customer.find(session[:guest_user_id] ||= create_guest_customer.id)

  rescue ActiveRecord::RecordNotFound # if session[:guest_user_id] invalid
    session[:guest_user_id] = nil
    guest_customer if with_retry
  end

  private

  # called (once) when the customer logs in, insert any code your application needs
  # to hand off from guest_customer to current_customer.
  def logging_in
    # For example:
    # guest_comments = guest_customer.comments.all
    # guest_comments.each do |comment|
    # comment.user_id = current_customer.id
    # comment.save!
    # end
  end

  def create_guest_customer
    user = Customer.create(:email => "guest_#{Time.now.to_i}#{rand(100)}@example.com")
    user.save!(:validate => false)
    session[:guest_user_id] = user.id
    user
  end

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def update
    @customer = Customer.find(params[:id])
    @order = @customer.orders.last

    if @customer.update_attributes(customer_params)
      @order.confirm
      redirect_to(root_path, notice: "Your order has been placed successfully")
    else
      redirect_to  order_shipping_info_path(@order.id)
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:first_name,
                                     :last_name,
                                     :email,
                                     :street,
                                     :city,
                                     :state,
                                     :postal_code,
                                     :country
                                    )
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :get_all_products, only: [:new, :create]
  def new
    @order = Order.new
  end

  def create
    @order = Order.create(customer: current_or_guest_customer)
    # add selected products to the order
      @products.each do |product|
        if params[product.name]
          @order.add_product(product.name, params["#{product.name}_qty"])
        end
      end

    respond_to do |f|
      if @order.save
        f.html { redirect_to order_shipping_info_path(@order.id) }
      else
        f.html { render :new }
      end
    end
  end

  def show
    @order = Order.find(params[:id])
  end

  def shipping_info
    @order = Order.find(params[:id])
    @customer = @order.customer
    unless @customer.valid?
      render :shipping_info
    end
  end

  private

  def get_all_products
    @products = Product.all
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title(separator = ' – ')
    [content_for(:title), 'Monster Beverage'].compact.join(separator)
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="content">
    &copy Monster Beverage Inc.
  </div>
</footer>

app/views/layouts/_topnav.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="nav-container">
    <a id='logo' href="/">Monster Beverage</a>
    <div class="shipped-counter col-md-2 nav-item pull-right">
      <strong>Orders shipped: <span id = 'total_order_shipped'><%= Order.shipped.count %></span></strong>
    </div>
    <div class="ounces-sold col-md-2 nav-item pull-right">
      <strong>Units sold: <span id = 'total_units_sold'><%= Order.units_sold %></span></strong>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>
    <%= page_title %>
  </title>
  <script type="text/javascript">
    window.pusher_key = '<%= Rails.application.secrets.pusher_key %>';
  </script>
  <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.0/css/font-awesome.min.css" media="screen" rel="stylesheet" type="text/css" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
      <%= csrf_meta_tags %>
</head>

<body>
  <div class="wrapper">
    <%= render 'layouts/topnav' %>
      <div class="container">
        <% if notice %>
          <p class="alert alert-success">
            <%= notice %>
          </p>
          <% end %>
            <% if alert %>
              <p class="alert alert-danger">
                <%= alert %>
              </p>
              <% end %>
                <%= yield %>
      </div>
      <table>
      <li class="clearfix">
        <% Order.lastest_order.each do |order| %>
          <h4>
            <div id= "order_feed#{order.id}">
             <%= "#{order.customer.first_name} just purchased from #{order.customer.city}, #{order.customer.country}" %>
          </div>
        </h4>
          <% end %>
      </li>
      </table>
      <%= render 'layouts/footer' %>
  </div>
</body>

</html>

app/views/orders/new.html.erb
<%= form_for @order, url: {action: "create"} do |f| %>
  <% @products.each do |product| %>
    <%= div_for product do %>
      <div class="row">
        <div class="name col-md-2">
          <h2><%= product.name %></h2>
        </div>

        <div class="description col-md-2">
          <h4><%= product.description %></h4>
        </div>

        <div class="cost col-md-2">
          <h5>$<%= product.cost %></h5>
        </div>

        <div class="col-md-1">
          <%= f.label :qty, "quantity" %>
          <%= number_field_tag("#{product.name}_qty".to_sym, nil, in: 1..10, value: 1, class: "form-control") %>
        </div>

        <div class="add-card col-md-4">
          <%= f.label "add to cart"%>
          <%= check_box_tag("#{product.name.to_sym}") %>
        </div>
      </div>
    <% end %>
  <% end %>
  <button id="checkout-btn" type="submit" class="btn btn-warning" style="float: right" >Continue to checkout</button>
<% end %>

app/views/orders/shipping_info.html.erb
<%= form_for @customer, :html => {:class => "form-group center"} do |f| %>
  <div class="cust-info">
    <div class="form-group">
      <div class="col-md-3">
        <%= f.label :first_name, "First name" %>
        <%= f.text_field :first_name, class: "form-control", placeholder: "first name" %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-md-3">
        <%= f.label :last_name, "Last name" %>
        <%= f.text_field :last_name, class: "form-control", placeholder: "last name" %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-md-3">
        <%= f.label :email, "Email" %>
        <%= f.email_field :email, class: "form-control", placeholder: "email address" %>
      </div>
    </div>
  </div>

  <div class="address">
    <div class="form-group">
      <div class="col-md-3">
        <%= f.label :street, "Street address" %>
        <%= f.text_field :street, class: "form-control", placeholder: "street address" %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-md-3">
        <%= f.label :city, "City" %>
        <%= f.text_field :city, class: "form-control", placeholder: "city" %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-md-3">
        <%= f.label :state, "State" %>
        <%= f.text_field :state, class: "form-control", placeholder: "state" %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-md-3">
        <%= f.label :country, "Country" %>
        <%= f.text_field :country, class: "form-control", placeholder: "country" %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-md-3">
        <%= f.label :postal_code, "Postal code" %>
        <%= f.text_field :postal_code, class: "form-control", placeholder: "post code" %>
      </div>
    </div>
  </div>

  <div class="order-preview col-md-12">
    <div class="row">
      <div class="col-md-3">
        <h2>Your Order:</h2>
      </div>
    </div>
    <% @order.products.each do |product| %>
      <div class="order-details row">
        <div class="col-md-2">
          <p><%= product.name %> x <%= product.qty %></p>
        </div>
        <div class="col-sm-1">
          <p>$<%= product.qty * product.cost %></p>
        </div>
      </div>
    <% end %>
    <div class="row">
      <div class="col-md-2">
        <strong>Total: </strong>
      </div>
      <div class="col-sm-1">
        <strong>$<%= @order.total_cost %></strong>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-4">
      <%= f.submit "Ship it!", class: "btn btn-lg btn-primary", style: "margin: 14px" %>
    </div>
  </div>
<% end %>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <h1>The best beverage ever!!!</h1>
  <div class="btn-group">
    <%= link_to 'Shop Now', new_order_path, class: "btn btn-success" %>
  </div>
</div>